// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmws18CAcTWf_cygNez9-GK67dsVh9d8k',
    appId: '1:34948950243:web:0422a0bff4e765d49f3dd6',
    messagingSenderId: '34948950243',
    projectId: 'fundev-x-1162d',
    authDomain: 'fundev-x-1162d.firebaseapp.com',
    storageBucket: 'fundev-x-1162d.firebasestorage.app',
    measurementId: 'G-NGEYGEHTBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYVQpohjnscoWBkJf2pW4Q3N5RhpAnN0',
    appId: '1:34948950243:android:13e76fd0cc448a9e9f3dd6',
    messagingSenderId: '34948950243',
    projectId: 'fundev-x-1162d',
    storageBucket: 'fundev-x-1162d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDna1olMZhbU0jwdzrX87bKPvBVEyWUPq4',
    appId: '1:34948950243:ios:c6076889b013c0cf9f3dd6',
    messagingSenderId: '34948950243',
    projectId: 'fundev-x-1162d',
    storageBucket: 'fundev-x-1162d.firebasestorage.app',
    iosBundleId: 'com.coderz.funDevx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDna1olMZhbU0jwdzrX87bKPvBVEyWUPq4',
    appId: '1:34948950243:ios:c6076889b013c0cf9f3dd6',
    messagingSenderId: '34948950243',
    projectId: 'fundev-x-1162d',
    storageBucket: 'fundev-x-1162d.firebasestorage.app',
    iosBundleId: 'com.coderz.funDevx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmws18CAcTWf_cygNez9-GK67dsVh9d8k',
    appId: '1:34948950243:web:38d08294b70db13b9f3dd6',
    messagingSenderId: '34948950243',
    projectId: 'fundev-x-1162d',
    authDomain: 'fundev-x-1162d.firebaseapp.com',
    storageBucket: 'fundev-x-1162d.firebasestorage.app',
    measurementId: 'G-Z5CPSHNPW3',
  );
}
